trigger:
- main
- feature
pool:
 name: dhurander
stages:
  - stage: terraforminit
    displayName: terraform init
    jobs:
      - job: 
        displayName: terraform init
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: '4.70.0'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'data'
            backendAzureRmStorageAccountName: 'stagefile123321'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'dev.terraform'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'data'
  - stage: manualapproval
    displayName: manual approval
    jobs:
      - job: 
        displayName: approval
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'sbicardankit144@gmail.com'
  - stage: terraformapply
    displayName: terraform & apply
    jobs:
      - job: TerraformApplyJob
        displayName: apply
        condition: succeeded()
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'data'
            backendAzureRmStorageAccountName: 'stagefile123321'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'dev.terraform'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'data'