trigger:
- main
pool:
 name: dhurander
stages:
  - stage: terraforminit
    displayName: terraform init
    jobs:
      - job: 
        displayName: terraform init
        steps:
        
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'terraform init -upgrade'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'data'
            backendAzureRmStorageAccountName: 'stagefile123321'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'dev.terraform'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'data'
        